# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bckt_tune <- function(n_sim, alpha, delta, ph2_size, n_samples, grid_dim, grid_radius, p, p_endpt, lmda_grid, start_seed = -1L, p_batch_size = -1L, n_thr = -1L, do_progress_bar = TRUE) {
    .Call(`_kevlar_bckt_tune`, n_sim, alpha, delta, ph2_size, n_samples, grid_dim, grid_radius, p, p_endpt, lmda_grid, start_seed, p_batch_size, n_thr, do_progress_bar)
}

bckt_fit <- function(n_sim, delta, ph2_size, n_samples, grid_dim, grid_radius, p, p_endpt, lmda, serialize_fname, start_seed = -1L, p_batch_size = -1L, n_thr = -1L, do_progress_bar = TRUE) {
    invisible(.Call(`_kevlar_bckt_fit`, n_sim, delta, ph2_size, n_samples, grid_dim, grid_radius, p, p_endpt, lmda, serialize_fname, start_seed, p_batch_size, n_thr, do_progress_bar))
}

eckt_tune <- function(n_sim, alpha, delta, n_samples, grid_radius, censor_time, lmda, lmda_lower, hzrd_rate, hzrd_rate_lower, thr_vec, start_seed = -1L, p_batch_size = -1L, n_thr = -1L, do_progress_bar = TRUE) {
    .Call(`_kevlar_eckt_tune`, n_sim, alpha, delta, n_samples, grid_radius, censor_time, lmda, lmda_lower, hzrd_rate, hzrd_rate_lower, thr_vec, start_seed, p_batch_size, n_thr, do_progress_bar)
}

eckt_fit <- function(n_sim, delta, n_samples, grid_radius, censor_time, lmda, lmda_lower, hzrd_rate, hzrd_rate_lower, thr, serialize_fname, start_seed = -1L, p_batch_size = -1L, n_thr = -1L, do_progress_bar = TRUE) {
    invisible(.Call(`_kevlar_eckt_fit`, n_sim, delta, n_samples, grid_radius, censor_time, lmda, lmda_lower, hzrd_rate, hzrd_rate_lower, thr, serialize_fname, start_seed, p_batch_size, n_thr, do_progress_bar))
}

unserialize <- function(fname) {
    .Call(`_kevlar_unserialize`, fname)
}

grid_radius <- function(n, lower, upper) {
    .Call(`_kevlar_grid_radius`, n, lower, upper)
}

make_grid <- function(n, lower, upper) {
    .Call(`_kevlar_make_grid`, n, lower, upper)
}

make_endpts <- function(n, lower, upper) {
    .Call(`_kevlar_make_endpts`, n, lower, upper)
}

