name: kevlar
channels:
  - conda-forge
dependencies:
# essentials
  - python
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - sympy
  - pandas

# some more nice stuff for easy dev.
  - pytest
  - pre-commit
  - black
  - flake8
  - isort
  - jupytext
  - cython
  - cxx-compiler
  - clang-tools
  - line_profiler
  - pip
  - seaborn

# numerical tools
  - jax
  - numpyro
  - pip:
    - setuptools
    - "pybind11[global]"
    - httpstan
    - pystan
    - cppimport
