cc_library(
    name = "kevlar",
    srcs = glob([
        "include/**/*.hpp",
        "include/**/*.cpp",
    ]),
    hdrs = glob(["include/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@eigen"],
)
