name: kevlar
channels:
  - conda-forge
dependencies:
# essentials
  - python=3.10
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - sympy
  - pandas

# some more nice stuff for easy dev.
  - pytest
  - pre-commit
  - black
  - cython
  - cxx-compiler
  - line_profiler
  - pip
  - seaborn

# numerical tools
  - pip:
    - setuptools
    - "pybind11[global]"
    - httpstan
    - pystan

