```{r}
library(INLA)
library(boot)
```

```{r}
# set up super simple simulated data.
# 50 patients for each of 4 trial groups. 
n_patients_per_group <- 50
n_groups <- 4
# The group effects are drawn from a distribution with mean 0.5 and variance 1.0
mean_effect <- 0.5
effect_var <- 1.0
t_i <- rnorm(n_groups, mean_effect, sqrt(effect_var))
# inverse logit to get probabilities from linear predictors.
p_i <- inv.logit(t_i)
```

```{r}
# simulate
n_sim <- 50
CIs <- array(numeric(), c(n_sim, n_groups, 2))
for (i in 1:n_sim) {
    y_i <- rbinom(n_groups, n_patients_per_group, p_i)
    df <- data.frame(y = y_i, gid = (1:n_groups))
    result <- inla(
        y ~ f(
            gid,
            model = "iid"
            ,hyper = list(theta = list(prior = "gaussian", param = c(0, 0.1)))
        ),
        data = df, 
        Ntrials = rep(n_patients_per_group, n_groups),
        family = "binomial",
        control.compute = list(
            config = TRUE,
            return.marginals.predictor = TRUE
        )
    )
    for (j in 1:n_groups) {
        CIs[i,j,] <- inla.hpdmarginal(0.95, result$marginals.linear.predictor[[j]])
    }
}
```

```{r}
theta_mat = t(matrix(rep(t_i, n_sim), ncol=n_sim))
n_correct = sum((CIs[,,1] < theta_mat) & (theta_mat < CIs[,,2]))
n_correct / (n_sim * n_groups)
```
