```{r}
library(INLA)
library(boot)
```

```{r}
set.seed(1000)
# set up super simple simulated data.
# 50 patients for each of 4 trial groups. 
n_patients_per_group <- 50
n_groups <- 4
# The group effects are drawn from a distribution with mean 0.5 and variance 1.0
mean_effect <- 0.5
effect_var <- 1.0
t_i <- rnorm(n_groups, mean_effect, sqrt(effect_var))
# inverse logit to get probabilities from linear predictors.
p_i <- inv.logit(t_i)
# simulate
y_i <- rbinom(n_groups, n_patients_per_group, p_i)
sprintf("%.16f", t_i)
sprintf("%.16f", p_i)
sprintf("%.16f", y_i)
```

```{r}
# Run INLA with a model where
# logit(p) = intercept + random_effect(drawn iid from normal)
# The prior on the random effect influences the sharing between groups. I
# haven't tuned this yet.
df <- data.frame(y = y_i, gid = (1:n_groups))
result <- inla(
    y ~ f(
        gid, 
        model = "iid",
        hyper = list(theta = list(prior = "gaussian", param = c(0, 0.1)))
    ),
    data = df, 
    Ntrials = rep(n_patients_per_group, n_groups),
    family = "binomial",
    control.compute = list(
        config = TRUE,
        return.marginals.predictor = TRUE
    )
)
summary(result)
# result.samp <- inla.posterior.sample(100, result)
# names(result.samp[[1]])
# print(result.samp[[1]])
```

```{r}
# Plot marginal PDFs.
# These will depend heavily on hyperparameter priors which I have just left default
# for now.
par(mfrow=c(2,2))
for (i in 1:n_groups) {
    theta_i <- result$marginals.linear.predictor[[i]][,1]
    density <- result$marginals.linear.predictor[[i]][,2]
    plot(theta_i, density, main=t_i[[i]])
    abline(v=mean(t_i), col="blue")
}
```

```{r}
# Print 95% confidence intervals for the linear predictors. 
# I'm not 100% sure these are correct, but they track correctly with the y_i
for (i in 1:n_groups) {
    print(t_i[[i]])
    print(inla.hpdmarginal(0.95, result$marginals.linear.predictor[[i]]))
}
```

```{r}
for (i in 1:n_groups) {
    print(y_i[[i]])
    print(inla.pmarginal(0, result$marginals.linear.predictor[[i]]))
}
```
