name: Push to Confirm

on:
  push:
    branches:
      - main
jobs:
  push_to_confirm:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # based on https://github.com/orgs/community/discussions/26323
    name: Trigger push to confirm
    steps:
      - name: Trigger push to confirm
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SUBREPO_BOT_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'Confirm-Solutions',
              repo: 'confirmasaurus',
              workflow_id: 'pull-from-imprint.yml',
              ref: 'main'
            })
            console.log(result)
